services:
  backend:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - postgress_shared_net

networks:
  postgress_shared_net:
    external: true
