import { Lock, FileText, Scale, User, Shield, DatabaseZap } from "lucide-react";

export function Trust() {
  return (
    <section id="governance" className="py-24 bg-[#F6F8FB]">
      <div className="container px-4 md:px-6 max-w-6xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-[#0B2A4A] mb-4">HIPAA-safe architecture and governance</h2>
          <p className="text-lg text-muted-foreground max-w-3xl mx-auto">
            PHI stays inside the protected audit system. Any AI assistance must operate on tokenized, hashed, or fully de-identified inputs and never on raw PHI.
          </p>
        </div>

        <div className="grid md:grid-cols-3 gap-8">
          {[
            {
              icon: FileText,
              title: "Deterministic dollar decisions",
              text: "Payment correctness, underpayment calculations, and coverage logic are rules-based and auditable — not generated by an LLM."
            },
            {
              icon: Scale,
              title: "Source-of-truth citations",
              text: "Each finding is tied back to a contract term, public fee schedule, locality file, or published payer rule."
            },
            {
              icon: Shield,
              title: "Minimum-necessary data handling",
              text: "Only the fields needed for adjudication and reporting are retained, with tenant isolation and controlled access by role."
            },
            {
              icon: Lock,
              title: "PHI boundary enforcement",
              text: "No raw PHI is sent to external LLM providers. If AI is used, identifiers must be tokenized or stripped first."
            },
            {
              icon: DatabaseZap,
              title: "Background audit agent constraints",
              text: "Background agents may monitor status, summarize counts, and queue alerts, but cannot export PHI or create unsupported findings."
            },
            {
              icon: User,
              title: "Human approval before action",
              text: "Admins and analysts review findings, packet drafts, and outbound recovery workflows before anything leaves the platform."
            }
          ].map((item) => (
            <div key={item.title} className="bg-white p-8 rounded-lg border border-border shadow-sm hover:shadow-md transition-shadow">
              <item.icon className="w-10 h-10 text-[#143A66] mb-4" />
              <h3 className="text-lg font-bold text-[#0B2A4A] mb-2">{item.title}</h3>
              <p className="text-muted-foreground text-sm leading-relaxed">{item.text}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
