"""added payment details in document

Revision ID: bac1d1dc91c0
Revises: 34403f6ddece
Create Date: 2026-01-29 13:38:40.701348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac1d1dc91c0'
down_revision: Union[str, None] = '34403f6ddece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server_default for existing rows, then remove default
    op.add_column('documents', sa.Column('receipt_amount', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('documents', sa.Column('contract_amount', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('documents', sa.Column('underpayment_amount', sa.Float(), nullable=False, server_default='0.0'))
    
    # Remove server defaults after adding columns (optional, keeps schema clean)
    op.alter_column('documents', 'receipt_amount', server_default=None)
    op.alter_column('documents', 'contract_amount', server_default=None)
    op.alter_column('documents', 'underpayment_amount', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'underpayment_amount')
    op.drop_column('documents', 'contract_amount')
    op.drop_column('documents', 'receipt_amount')
    # ### end Alembic commands ###
